export const days = [
  day("d0", "D0", "2026-07-28", "周二", "上海 → 香港 → 墨尔本", 31.2304, 121.4737, "上海出发，香港转机飞墨尔本", "出发日，香港转机 1h35m，夜航飞墨尔本。", "飞机上", "夜航为主，机场和机舱温差明显。", "随身带薄外套、颈枕、充电线和第一天入境资料。", "/itinerary/d0-shanghai-departure.png", "上海机场夜间出发"),
  day("d1", "D1", "2026-07-29", "周三", "墨尔本", -37.8136, 144.9631, "抵达墨尔本，Southbank 河岸夜景", "05:55 抵达后以恢复为主，不硬玩。", "Oaks Melbourne on Market Hotel", "墨尔本冬季约 6-14°C，早晚冷，多风，偶有阵雨。", "羽绒服或防风外套、毛衣、长裤、防水鞋。", "/itinerary/melbourne-city-morning.png", "墨尔本清晨城市街景"),
  day("d2", "D2", "2026-07-30", "周四", "墨尔本市区", -37.8136, 144.9631, "图书馆、市集、巷弄与 NGV", "城市适应 + 咖啡 + 市集 + 巷弄艺术 + 轻量文化体验。", "Oaks Melbourne on Market Hotel", "墨尔本冬季约 6-14°C，早晚冷，多风，偶有阵雨。", "防风外套比单纯厚毛衣更实用，雨天鞋子尽量防水。", "/itinerary/d2-melbourne-laneways-market.png", "墨尔本巷弄与市集"),
  day("d3", "D3", "2026-07-31", "周五", "墨尔本 → Apollo Bay", -38.7599, 143.6692, "大洋路 Road Trip Day 1", "冲浪海岸、灯塔、纪念拱门、小镇节奏和海岸观景逐步展开。", "Seaview Motel & Apartments", "维州南海岸冬季多风，体感比温度更冷。", "防风外套、长裤、防滑鞋；车上备水和零食。", "/itinerary/great-ocean-road-coast.png", "大洋路海岸线"),
  day("d4", "D4", "2026-08-01", "周六", "Apollo Bay → Port Campbell", -38.6191, 142.9956, "十二使徒岩与 Loch Ard Gorge", "大洋路景观最强的一天，把核心海岸地貌看扎实。", "Southern Ocean Villas", "海岸风大，步道和台阶雨后湿滑。", "防风外套、防水鞋；拍照时不要太靠近海浪。", "/itinerary/d4-twelve-apostles-gorge.png", "十二使徒岩与峡谷海岸"),
  day("d5", "D5", "2026-08-02", "周日", "Port Campbell → 墨尔本机场", -37.669, 144.841, "清晨补拍，内陆回机场", "清晨补拍 + Port Campbell 以西海岸点 + 内陆回程。", "Holiday Inn Melbourne Airport", "早晨海边冷，回程时间长。", "早上防风保暖，下午回机场前预留加油和还车时间。", "/itinerary/d5-port-campbell-morning.png", "Port Campbell 清晨海岸"),
  day("d6", "D6", "2026-08-03", "周一", "墨尔本 → 凯恩斯", -16.9186, 145.7781, "飞进热带，Esplanade Lagoon", "从冬天飞进热带，轻松适应。", "Southern Cross Atrium Apartments", "凯恩斯约 17-26°C，旱季，阳光充足。", "短袖、防晒衣、墨镜、帽子；机舱和室内空调可能冷。", "/itinerary/cairns-reef-lagoon.png", "凯恩斯热带海岸"),
  day("d7", "D7", "2026-08-04", "周二", "凯恩斯", -16.9186, 145.7781, "Reef Magic 外礁一日游", "凯恩斯最重要的一天，平台型外礁体验更稳。", "Southern Cross Atrium Apartments", "海上日晒强，船舱空调可能很冷。", "防晒衣比防晒霜更重要，带薄外套并提前吃晕船药。", "/itinerary/d7-great-barrier-reef-pontoon.png", "大堡礁外礁平台"),
  day("d8", "D8", "2026-08-05", "周三", "丹翠雨林", -16.1705, 145.4185, "丹翠雨林 + Cape Tribulation 小团", "交给当地司机和向导，看热带雨林、鳄鱼河道和雨林入海。", "Southern Cross Atrium Apartments", "热带雨林湿润，车内空调可能冷。", "短袖、防晒、防蚊、帽子、薄外套；不建议下海游泳。", "/itinerary/daintree-rainforest.png", "丹翠雨林"),
  day("d9", "D9", "2026-08-06", "周四", "阿瑟顿高原", -17.2706, 145.5831, "火山湖、巨树、小镇与瀑布", "轻量自驾，用湖、巨树、高原小镇和经典瀑布补足内陆自然体验。", "Southern Cross Atrium Apartments", "高原比凯恩斯海边更清凉。", "短袖加薄外套，瀑布和雨林步道注意防滑。", "/itinerary/d9-atherton-tablelands-waterfall.png", "阿瑟顿高原瀑布"),
  day("d10", "D10", "2026-08-07", "周五", "凯恩斯", -16.9186, 145.7781, "Rusty's Market 与休息整理", "真正的恢复日，洗衣、整理行李、热带水果和海边散步。", "Southern Cross Atrium Apartments", "凯恩斯约 17-26°C，户外热，室内空调冷。", "轻便夏装，随身带薄外套；今天不要再临时加长线。", "/itinerary/d10-cairns-rustys-market.png", "凯恩斯市场与海滨"),
  day("d11", "D11", "2026-08-08", "周六", "凯恩斯 → 悉尼", -33.8688, 151.2093, "转场悉尼，The Rocks 与海港夜景", "清晨转场日，从热带回到冬季海港城市。", "Oaks Sydney Goldsbrough Suites", "悉尼约 9-18°C，早晚凉，海边防风。", "薄羽绒、风衣或卫衣；从凯恩斯上飞机随身带外套。", "/itinerary/d11-sydney-arrival-rocks.png", "悉尼 The Rocks 夜景"),
  day("d12", "D12", "2026-08-09", "周日", "悉尼市区", -33.8688, 151.2093, "歌剧院、植物园、Mrs Macquarie's Chair", "悉尼明信片路线，海港桥与歌剧院同框。", "Oaks Sydney Goldsbrough Suites", "悉尼冬季晴天概率较好，早晚凉。", "薄羽绒或风衣，海港边风大时注意保暖。", "/itinerary/d12-sydney-opera-garden.png", "悉尼歌剧院与植物园"),
  day("d13", "D13", "2026-08-10", "周一", "悉尼弹性一日游", -33.8688, 151.2093, "南海岸或蓝山二选一", "根据天气决定 Grand Pacific Drive / Sea Cliff Bridge 或 Blue Mountains。", "Oaks Sydney Goldsbrough Suites", "南海岸看晴天，蓝山雾雨会影响景观且更冷。", "看天气定路线；海边防风，蓝山加厚外套。", "/itinerary/d13-blue-mountains-seacliff-choice.png", "蓝山与南海岸弹性路线"),
  day("d14", "D14", "2026-08-11", "周二", "悉尼", -33.8688, 151.2093, "出海观鲸 + Bondi", "冬季悉尼海洋体验，上午观鲸，下午 Bondi 海岸。", "Oaks Sydney Goldsbrough Suites", "出海风大，海况影响体感。", "提前吃晕船药，穿防风外套；Bondi 步道不必全程走完。", "/itinerary/d14-whale-bondi-coast.png", "悉尼观鲸与 Bondi 海岸"),
  day("d15", "D15", "2026-08-12", "周三", "悉尼", -33.8688, 151.2093, "Manly Ferry + 最后采购 + Cafe Sydney", "轻松收尾，完成购物和退税准备，晚上告别晚餐。", "Oaks Sydney Goldsbrough Suites", "悉尼早晚凉，渡轮上海风明显。", "薄外套随身；晚餐注意 smart dress code。", "/itinerary/sydney-harbor-evening.png", "悉尼海港黄昏"),
  day("d16", "D16", "2026-08-13", "周四", "悉尼 → 香港 → 上海", -33.9399, 151.1753, "返程与 TRS 退税", "提前到机场办理退税和返程手续。", "-", "机场和机舱温差明显。", "提前整理退税物品和购物小票，随身带薄外套。", "/itinerary/d16-return-flight.png", "澳洲旅行返程"),
];

export const blocks = [
  block("d0", 10, "全天", "上海 → 香港 → 墨尔本", "出发，香港转机 1h35m，夜航飞墨尔本", "旅程开始", "护照、签证、酒店信息和第一晚随身物品放随身包", "flight-cathay"),
  block("d1", 10, "早上", "墨尔本机场 → CBD", "入境、取行李，打车或 SkyBus 进城", "初到澳洲，适应气候", "4 人同行加行李较多，打车或 Uber 可能更舒服", "mel-airport-map,oaks-market-map"),
  block("d1", 20, "下午", "酒店", "入住、补觉、洗澡", "调整时差", "这是保证后面自驾状态的关键", "oaks-market-booking"),
  block("d1", 30, "傍晚", "Southbank / Yarra River", "河边散步与河畔晚餐", "墨尔本夜景、城市氛围", "轻松走走即可，不要暴走", "southbank-map"),
  block("d2", 10, "上午", "State Library / QVM", "州立图书馆经典阅览室 + Queen Victoria Market", "历史建筑与市井生活", "周四 QVM 开放，图书馆短暂停留拍照即可", "state-library-map,qvm-map"),
  block("d2", 20, "中午", "Degraves Street / Hardware Lane", "Brunch 或简餐，体验咖啡巷弄", "墨尔本 laneway culture", "如果 QVM 已吃多，这里可以只喝咖啡", "degraves-map"),
  block("d2", 30, "下午", "Hosier Lane / NGV", "涂鸦巷拍照，随后去 NGV 看展或休息", "街头艺术 + 文艺墨尔本", "Hosier Lane 20-30 分钟即可，NGV 适合避风避寒", "hosier-map,ngv-map"),
  block("d2", 40, "傍晚", "Southbank / Skydeck", "天气好上 Skydeck，否则 Southbank 河边晚餐", "河岸夜景 / 城市高空视角", "Skydeck 看能见度和体力，不提前锁死", "skydeck-map"),
  block("d3", 10, "上午", "墨尔本 → Torquay", "机场提车出发，进入大洋路", "Road trip 正式开始", "右舵第一天不要赶，Geelong 不绕", "torquay-map"),
  block("d3", 20, "上午", "Bells Beach / Split Point Lighthouse", "冲浪海岸与白色灯塔", "海浪、悬崖、灯塔", "风大，短停即可", "bells-map,split-point-map"),
  block("d3", 30, "中午", "Memorial Arch / Teddy's Lookout / Lorne", "纪念拱门拍照，Lorne 午餐补给", "经典海岸构图和海滨小镇", "Lorne 是休息重点，不赶", "memorial-arch-map,teddys-map,lorne-map"),
  block("d3", 40, "下午", "Kennett River → Apollo Bay", "找考拉，短停 Cape Patton Lookout", "桉树、野生考拉、高位海岸远景", "抬头看树，不保证但高概率", "kennett-map,apollo-map"),
  block("d4", 10, "上午", "Maits Rest Rainforest Walk", "雨林短步道", "冬日湿润雨林", "步道轻松，注意地面湿滑", "maits-rest-map"),
  block("d4", 20, "中午前后", "Gibson Steps", "下到海滩看悬崖与海蚀柱", "人物比例感强", "看开放情况和风浪，不要太靠近海浪", "gibson-steps-map"),
  block("d4", 30, "下午", "Twelve Apostles", "主观景台看十二使徒岩", "世界级海岸地貌", "左侧平台更适合拍海岸线纵深", "twelve-apostles-map"),
  block("d4", 40, "下午", "Loch Ard Gorge / Razorback", "峡谷、海湾、海蚀地貌和岩脊", "D4 核心拍摄点", "认真留时间，不要只拍一张就走", "loch-ard-map,razorback-map"),
  block("d5", 10, "早上", "Twelve Apostles / Loch Ard Gorge", "清晨补拍", "光线柔和，人相对少", "如果 D4 天气不好，这天可补救", "twelve-apostles-map,loch-ard-map"),
  block("d5", 20, "上午 / 中午", "London Arch / The Grotto", "看海蚀拱门和海水窗口", "Port Campbell 以西经典点", "雨后台阶湿滑，短停即可", "london-arch-map,grotto-map"),
  block("d5", 30, "下午", "Colac → Melbourne Airport", "午餐、加油、休息，回机场还车", "内陆牧场风光", "还车预留加油、找还车点和整理行李时间", "colac-map,mel-airport-map"),
  block("d6", 10, "上午", "墨尔本机场", "VA1291 飞往凯恩斯", "气候切换明显", "国内航班预留行李额", "mel-airport-map,cairns-airport-map"),
  block("d6", 20, "下午", "Esplanade Lagoon", "免费泻湖泳池和海滨散步", "度假感拉满", "泳衣可提前放随身包", "cairns-lagoon-map"),
  block("d6", 30, "晚上", "Cairns Night Markets", "夜市、简餐、纪念品", "热闹轻松", "今日不安排正式大餐", "cairns-night-market-map"),
  block("d7", 10, "早上", "凯恩斯码头", "登船出海前往外堡礁", "前往 Reef Magic 平台", "提前吃晕船药，不要卡点到码头", "reef-fleet-terminal-map,reef-magic-official"),
  block("d7", 20, "全天", "Outer Reef Pontoon", "浮潜、半潜艇、玻璃底船、平台体验", "珊瑚、热带鱼、大堡礁体验", "防晒衣比防晒霜更重要，船舱空调可能很冷", "reef-magic-official"),
  block("d7", 30, "晚上", "码头附近", "Salt House / Dundee's / Prawn Star 可选", "海边晚餐", "晚上不要订太正式的餐厅", "prawn-star-map,salt-house-map"),
  block("d8", 10, "清晨", "凯恩斯酒店 → 丹翠方向", "6:55am 酒店门口集合，跟团车北上", "不用自驾，沿途可休息看风景", "早上提前吃一点，带水、防晒、帽子和薄外套", "billy-tea-official"),
  block("d8", 20, "上午", "Daintree River / Rainforest", "鳄鱼游船、雨林步道", "野生鳄鱼、鸟类、红树林、热带雨林生态", "野生动物不保证，但 Daintree River 是经典鳄鱼河道", "daintree-river-map"),
  block("d8", 30, "下午", "Cape Tribulation", "雨林入海、海滩短停留", "这天最特别的画面", "不建议下海游泳，注意鳄鱼、水母和警示牌", "cape-trib-map"),
  block("d8", 40, "下午后段", "Daintree Ferry / Ice Cream", "渡河、热带水果冰淇淋", "only here 体验", "冰淇淋已包含在 Billy Tea 行程内", "daintree-icecream-map"),
  block("d9", 10, "早上", "凯恩斯 → Lake Eacham", "取车后开上 Atherton Tablelands", "从热带海边进入清凉高原", "8:30-9:00 出发比较理想", "lake-eacham-map"),
  block("d9", 20, "上午", "Curtain Fig Tree", "看巨型帘状无花果树", "热带森林里的巨大自然装置", "停留 20-30 分钟即可", "curtain-fig-map"),
  block("d9", 30, "中午", "Yungaburra / Gallo Dairyland", "小镇午餐、咖啡、奶制品、巧克力", "高原小镇和牧场氛围", "适合中段坐下来休息", "yungaburra-map,gallo-map"),
  block("d9", 40, "下午", "Millaa Millaa Falls", "瀑布短停留、拍照", "阿瑟顿视觉高潮", "优先 Millaa Millaa，体力够再加 Ellinjaa", "millaa-map"),
  block("d10", 10, "上午", "Rusty's Market", "买热带水果、咖啡、简单早餐", "周五正好开市", "买能当天吃完或带上飞机前吃完的", "rustys-map"),
  block("d10", 20, "中午 / 下午", "酒店 / Esplanade Lagoon", "休息、泳池、洗衣、整理行李", "保证第二天清晨转场不崩", "Jetstar 行李控制在 20kg 内，提前分装", "cairns-lagoon-map"),
  block("d10", 30, "晚上", "Prawn Star / Salt House / Night Market", "海鲜或轻松简餐", "凯恩斯最后一晚", "早点吃，早点睡", "prawn-star-map,salt-house-map"),
  block("d11", 10, "清晨", "凯恩斯酒店 → 机场 T2", "早起退房，打车或 Uber 前往机场", "转场日开始", "前一晚必须完成打包", "cairns-airport-map"),
  block("d11", 20, "下午", "Darling Harbour / 酒店周边", "轻松适应，简单午餐或休息", "不硬玩", "可在酒店附近熟悉环境", "oaks-sydney-map,darling-harbour-map"),
  block("d11", 30, "傍晚 / 晚上", "The Rocks / Circular Quay", "岩石区散步晚餐，环形码头看夜景", "悉尼开场画面", "轻松看夜景即可", "the-rocks-map,circular-quay-map"),
  block("d12", 10, "上午", "Circular Quay / Opera House", "歌剧院外观或内部导览", "悉尼核心地标", "中文导览可提前订", "opera-house-map,opera-house-official"),
  block("d12", 20, "中午 / 下午", "Royal Botanic Garden / Mrs Macquarie's Chair", "植物园散步，拍歌剧院和海港桥同框", "标准明信片角度", "晴天很好看", "botanic-garden-map,mrs-macquarie-map"),
  block("d12", 30, "傍晚 / 晚上", "QVB / Darling Harbour", "购物、室内休息、晚餐", "建筑漂亮，城市夜景", "商店关门较早", "qvb-map"),
  block("d13", 10, "Option A", "Blue Mountains", "Echo Point、Leura、Scenic World", "澳洲经典山地景观", "晴朗但海边风大时适合选蓝山", "blue-mountains-map,scenic-world-official"),
  block("d13", 20, "Option B", "Grand Pacific Drive", "Royal National Park、Sea Cliff Bridge、Wollongong、Kiama", "明亮海岸公路", "晴天且想开海边路时优先", "sea-cliff-map,kiama-map"),
  block("d14", 10, "上午", "Circular Quay / Darling Harbour", "出海观鲸", "座头鲸迁徙季", "提前吃晕船药，穿防风外套", "whale-watch-official"),
  block("d14", 20, "下午", "Bondi Beach / Icebergs", "海滩散步、Icebergs 拍照", "悉尼最有名海滩", "冬天不晒，适合走", "bondi-map,icebergs-map"),
  block("d14", 30, "傍晚", "Bondi to Coogee Coastal Walk", "走一段悬崖步道", "海岸线和 Tamarama 俯拍", "不必全程走完", "tamarama-map"),
  block("d15", 10, "上午", "Circular Quay → Manly", "坐 Ferry 去 Manly", "渡轮本身就是海港巡游", "坐船看歌剧院和海港桥角度很好", "manly-ferry-map"),
  block("d15", 20, "下午", "QVB / Chemist Warehouse / 超市", "最后采购", "药妆、保健品、伴手礼", "今天必须买完，回酒店整理退税物品", "qvb-map"),
  block("d15", 30, "晚上", "Cafe Sydney", "告别晚餐", "海港景观 + seafood / modern Australian", "建议 18:00-19:00，注意 smart dress code", "cafe-sydney-map,cafe-sydney-official"),
  block("d16", 10, "上午", "悉尼机场", "办理 TRS 退税，登机返程", "满载而归", "提前下载 TRS App 填好信息", "sydney-airport-map,trs-official"),
];

export const resources = [
  resource("flight-cathay", "国泰航空", "official", "https://www.cathaypacific.com/", "", "", "航司官网"),
  resource("mel-airport-map", "墨尔本机场", "map", "https://www.google.com/maps/search/?api=1&query=Melbourne+Airport", "", "", "Google Maps"),
  resource("oaks-market-map", "Oaks Melbourne on Market Hotel", "map", "https://www.google.com/maps/search/?api=1&query=Oaks+Melbourne+on+Market+Hotel", "", "", "Google Maps"),
  resource("oaks-market-booking", "Oaks Melbourne on Market", "booking", "https://www.oakshotels.com/en/oaks-on-market", "", "", "酒店官网"),
  resource("southbank-map", "Southbank", "map", "https://www.google.com/maps/search/?api=1&query=Southbank+Melbourne", "", "", "Google Maps"),
  resource("state-library-map", "State Library of Victoria", "map", "https://www.google.com/maps/search/?api=1&query=State+Library+of+Victoria", "", "", "Google Maps"),
  resource("qvm-map", "Queen Victoria Market", "map", "https://www.google.com/maps/search/?api=1&query=Queen+Victoria+Market", "", "", "Google Maps"),
  resource("degraves-map", "Degraves Street", "map", "https://www.google.com/maps/search/?api=1&query=Degraves+Street+Melbourne", "", "", "Google Maps"),
  resource("hosier-map", "Hosier Lane", "map", "https://www.google.com/maps/search/?api=1&query=Hosier+Lane+Melbourne", "", "", "Google Maps"),
  resource("ngv-map", "NGV", "map", "https://www.google.com/maps/search/?api=1&query=National+Gallery+of+Victoria", "", "", "Google Maps"),
  resource("skydeck-map", "Melbourne Skydeck", "map", "https://www.google.com/maps/search/?api=1&query=Melbourne+Skydeck", "", "", "Google Maps"),
  resource("torquay-map", "Torquay", "map", "https://www.google.com/maps/search/?api=1&query=Torquay+Victoria", "", "", "Google Maps"),
  resource("bells-map", "Bells Beach", "map", "https://www.google.com/maps/search/?api=1&query=Bells+Beach+Victoria", "", "", "Google Maps"),
  resource("split-point-map", "Split Point Lighthouse", "map", "https://www.google.com/maps/search/?api=1&query=Split+Point+Lighthouse", "", "", "Google Maps"),
  resource("memorial-arch-map", "Great Ocean Road Memorial Arch", "map", "https://www.google.com/maps/search/?api=1&query=Great+Ocean+Road+Memorial+Arch", "", "", "Google Maps"),
  resource("teddys-map", "Teddy's Lookout", "map", "https://www.google.com/maps/search/?api=1&query=Teddy%27s+Lookout+Lorne", "", "", "Google Maps"),
  resource("lorne-map", "Lorne", "map", "https://www.google.com/maps/search/?api=1&query=Lorne+Victoria", "", "", "Google Maps"),
  resource("kennett-map", "Kennett River", "map", "https://www.google.com/maps/search/?api=1&query=Kennett+River+Victoria", "", "", "Google Maps"),
  resource("apollo-map", "Apollo Bay", "map", "https://www.google.com/maps/search/?api=1&query=Apollo+Bay+Victoria", "", "", "Google Maps"),
  resource("maits-rest-map", "Maits Rest Rainforest Walk", "map", "https://www.google.com/maps/search/?api=1&query=Maits+Rest+Rainforest+Walk", "", "", "Google Maps"),
  resource("gibson-steps-map", "Gibson Steps", "map", "https://www.google.com/maps/search/?api=1&query=Gibson+Steps", "", "", "Google Maps"),
  resource("twelve-apostles-map", "Twelve Apostles", "map", "https://www.google.com/maps/search/?api=1&query=Twelve+Apostles+Victoria", "", "", "Google Maps"),
  resource("loch-ard-map", "Loch Ard Gorge", "map", "https://www.google.com/maps/search/?api=1&query=Loch+Ard+Gorge", "", "", "Google Maps"),
  resource("razorback-map", "The Razorback", "map", "https://www.google.com/maps/search/?api=1&query=The+Razorback+Port+Campbell", "", "", "Google Maps"),
  resource("london-arch-map", "London Arch", "map", "https://www.google.com/maps/search/?api=1&query=London+Arch+Victoria", "", "", "Google Maps"),
  resource("grotto-map", "The Grotto", "map", "https://www.google.com/maps/search/?api=1&query=The+Grotto+Port+Campbell", "", "", "Google Maps"),
  resource("colac-map", "Colac", "map", "https://www.google.com/maps/search/?api=1&query=Colac+Victoria", "", "", "Google Maps"),
  resource("cairns-airport-map", "凯恩斯机场", "map", "https://www.google.com/maps/search/?api=1&query=Cairns+Airport", "", "", "Google Maps"),
  resource("cairns-lagoon-map", "Esplanade Lagoon", "map", "https://www.google.com/maps/search/?api=1&query=Cairns+Esplanade+Lagoon", "", "", "Google Maps"),
  resource("cairns-night-market-map", "Cairns Night Markets", "map", "https://www.google.com/maps/search/?api=1&query=Cairns+Night+Markets", "", "", "Google Maps"),
  resource("reef-fleet-terminal-map", "Reef Fleet Terminal", "map", "https://www.google.com/maps/search/?api=1&query=Reef+Fleet+Terminal+Cairns", "", "", "Google Maps"),
  resource("reef-magic-official", "Reef Magic", "official", "https://www.reefmagic.com.au/", "", "", "官网"),
  resource("prawn-star-map", "Prawn Star", "restaurant", "https://www.google.com/maps/search/?api=1&query=Prawn+Star+Cairns", "", "", "Google Maps"),
  resource("salt-house-map", "Salt House", "restaurant", "https://www.google.com/maps/search/?api=1&query=Salt+House+Cairns", "", "", "Google Maps"),
  resource("billy-tea-official", "Billy Tea Safaris", "official", "https://www.billytea.com.au/", "", "", "官网"),
  resource("daintree-river-map", "Daintree River", "map", "https://www.google.com/maps/search/?api=1&query=Daintree+River", "", "", "Google Maps"),
  resource("cape-trib-map", "Cape Tribulation", "map", "https://www.google.com/maps/search/?api=1&query=Cape+Tribulation", "", "", "Google Maps"),
  resource("daintree-icecream-map", "Daintree Ice Cream Company", "restaurant", "https://www.google.com/maps/search/?api=1&query=Daintree+Ice+Cream+Company", "", "", "Google Maps"),
  resource("lake-eacham-map", "Lake Eacham", "map", "https://www.google.com/maps/search/?api=1&query=Lake+Eacham", "", "", "Google Maps"),
  resource("curtain-fig-map", "Curtain Fig Tree", "map", "https://www.google.com/maps/search/?api=1&query=Curtain+Fig+Tree", "", "", "Google Maps"),
  resource("yungaburra-map", "Yungaburra", "map", "https://www.google.com/maps/search/?api=1&query=Yungaburra", "", "", "Google Maps"),
  resource("gallo-map", "Gallo Dairyland", "restaurant", "https://www.google.com/maps/search/?api=1&query=Gallo+Dairyland", "", "", "Google Maps"),
  resource("millaa-map", "Millaa Millaa Falls", "map", "https://www.google.com/maps/search/?api=1&query=Millaa+Millaa+Falls", "", "", "Google Maps"),
  resource("rustys-map", "Rusty's Market", "map", "https://www.google.com/maps/search/?api=1&query=Rusty%27s+Market+Cairns", "", "", "Google Maps"),
  resource("oaks-sydney-map", "Oaks Sydney Goldsbrough Suites", "map", "https://www.google.com/maps/search/?api=1&query=Oaks+Sydney+Goldsbrough+Suites", "", "", "Google Maps"),
  resource("darling-harbour-map", "Darling Harbour", "map", "https://www.google.com/maps/search/?api=1&query=Darling+Harbour+Sydney", "", "", "Google Maps"),
  resource("the-rocks-map", "The Rocks", "map", "https://www.google.com/maps/search/?api=1&query=The+Rocks+Sydney", "", "", "Google Maps"),
  resource("circular-quay-map", "Circular Quay", "map", "https://www.google.com/maps/search/?api=1&query=Circular+Quay+Sydney", "", "", "Google Maps"),
  resource("opera-house-map", "Sydney Opera House", "map", "https://www.google.com/maps/search/?api=1&query=Sydney+Opera+House", "", "", "Google Maps"),
  resource("opera-house-official", "Sydney Opera House Tour", "official", "https://www.sydneyoperahouse.com/tours-and-experiences", "", "", "官网"),
  resource("botanic-garden-map", "Royal Botanic Garden Sydney", "map", "https://www.google.com/maps/search/?api=1&query=Royal+Botanic+Garden+Sydney", "", "", "Google Maps"),
  resource("mrs-macquarie-map", "Mrs Macquarie's Chair", "map", "https://www.google.com/maps/search/?api=1&query=Mrs+Macquarie%27s+Chair", "", "", "Google Maps"),
  resource("qvb-map", "QVB", "map", "https://www.google.com/maps/search/?api=1&query=Queen+Victoria+Building+Sydney", "", "", "Google Maps"),
  resource("blue-mountains-map", "Blue Mountains", "map", "https://www.google.com/maps/search/?api=1&query=Blue+Mountains+Echo+Point", "", "", "Google Maps"),
  resource("scenic-world-official", "Scenic World", "official", "https://www.scenicworld.com.au/", "", "", "官网"),
  resource("sea-cliff-map", "Sea Cliff Bridge", "map", "https://www.google.com/maps/search/?api=1&query=Sea+Cliff+Bridge", "", "", "Google Maps"),
  resource("kiama-map", "Kiama Blowhole", "map", "https://www.google.com/maps/search/?api=1&query=Kiama+Blowhole", "", "", "Google Maps"),
  resource("whale-watch-official", "Whale Watching Sydney", "booking", "https://www.whalewatchingsydney.com.au/", "", "", "预订参考"),
  resource("bondi-map", "Bondi Beach", "map", "https://www.google.com/maps/search/?api=1&query=Bondi+Beach", "", "", "Google Maps"),
  resource("icebergs-map", "Bondi Icebergs", "restaurant", "https://www.google.com/maps/search/?api=1&query=Bondi+Icebergs", "", "", "Google Maps"),
  resource("tamarama-map", "Tamarama Beach", "map", "https://www.google.com/maps/search/?api=1&query=Tamarama+Beach", "", "", "Google Maps"),
  resource("manly-ferry-map", "Manly Ferry", "map", "https://www.google.com/maps/search/?api=1&query=Manly+Ferry+Sydney", "", "", "Google Maps"),
  resource("cafe-sydney-map", "Cafe Sydney", "restaurant", "https://www.google.com/maps/search/?api=1&query=Cafe+Sydney", "", "", "Google Maps"),
  resource("cafe-sydney-official", "Cafe Sydney", "official", "https://cafesydney.com/", "", "", "官网"),
  resource("sydney-airport-map", "悉尼机场", "map", "https://www.google.com/maps/search/?api=1&query=Sydney+Airport", "", "", "Google Maps"),
  resource("trs-official", "TRS 退税", "official", "https://www.abf.gov.au/entering-and-leaving-australia/tourist-refund-scheme", "", "", "澳洲边防官网"),
];

function day(day_id, day_label, date, weekday, city, lat, lon, title, focus, lodging, climate_note, clothing_note, cover_image_url, cover_image_alt) {
  return { day_id, day_label, date, weekday, city, lat, lon, title, focus, lodging, climate_note, clothing_note, cover_image_url, cover_image_alt };
}

function block(day_id, sort_order, period, place, activity, highlight, tip, resource_ids = "") {
  return { day_id, sort_order, period, place, activity, highlight, tip, resource_ids };
}

function resource(resource_id, title, type, url, image_url, image_alt, source_note) {
  return { resource_id, title, type, url, image_url, image_alt, source_note };
}
